### ISSUE TITLE
Реализация интерфейса

### ISSUE THREAD

**Issue by avasyukov** [Shrulk/intAVLtree#1]
Таки должен быть реализован именно выданный интерфейс:
```
class Container
{
public:
    // Виртуальные методы, должны быть реализованы вашим контейнером
    virtual void insert(int value) = 0;
    virtual bool exists(int value) = 0;
    virtual void remove(int value) = 0;

    // И этот тоже, хотя к нему потом ещё вернёмся
    virtual void print() = 0;
    
    // Виртуальный деструктор (пока просто поверьте, что он нужен)
    virtual ~Container() { };
};
```
Шаблонизация - ок, оставляйте, раз она уже есть. Но имена публичных методов интерфейса нужно сохранить.

Причина: в живом проекте в реальной жизни физически не будет возможности что-нибудь дописать в интерфейс или изменить его. Он есть такой, какой есть, ничего в его сигнатуре изменить невозможно.

**Comment by Shrulk** [comment]
Изменил интерфейс на выданный

**Comment by avasyukov** [comment]
Сойдёт. Не очень ясно, зачем было шаблонизировать Container (тем более, оставив прибитые гвоздями int-ы во всех параметрах). Но к этому всё равно ещё вернёмся на второй итерации задачи.
